Repository italia-opensource/awesome-italia-innovative-companies, pull requests merged in 2022-09, with the labels that each got.

#1 Feat/add first startup
  CONTRIBUTING.md
  cli.py
  data/.gitkeep
  data/neulabs.json
  website/docusaurus.config.js
  website/src/components/TableFeatures/index.tsx
  website/src/pages/index.tsx
Labels: feature: request

#2 hotfix
  data/neulabs.json
  website/docusaurus.config.js
Labels: bug

#3 feat: add startups
  CONTRIBUTING.md
  cli.py
  data/jobtech.json
  data/prima.json
  data/satispay.json
  data/scalapay.json
  data/scuter.json
  data/yolo.json
  data/zappyrent.json
Labels: feature: new startup

#4 feat: add startups
  CONTRIBUTING.md
  cli.py
  data/amusi.json
  data/neulabs.json
  data/vitavi.json
Labels: feature: new startup

#5 chore!: rename repo from 'startups' to 'companies'
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  CONTRIBUTING.md
  README.md
  cli.py
  website/docusaurus.config.js
  website/src/components/TableFeatures/index.tsx
  website/src/pages/index.tsx
Labels: feature: request

#7 Feat/add companies1
  .github/ISSUE_TEMPLATE/QUESTION.yml
  CONTRIBUTING.md
  cli.py
  data/casavo.json
  data/dorbit.json
  data/enelx.json
  data/genomeup.json
  data/musement.json
  data/musixmatch.json
  data/nuvolaris.json
  data/wiseair.json
Labels: feature: new startup

#9 Aggiunta di Tirasa
  data/tirasa.json
Labels: feature: new company

#12 Added Mia-Care
  data/mia-care.json
Labels: feature: fix company

#11 Added Mia-FinTech
  data/mia-fintech.json
Labels: feature: new company

#13 feat: add companies
  CONTRIBUTING.md
  cli.py
  data/biorfarm.json
  data/orangefiber.json
  data/spartantech.json
  data/tiledesk.json
  data/weroad.json
Labels: feature: new company
